### ISSUE TITLE
Missing graphics

### ISSUE THREAD

**Issue by ScarlettGatelyMoore** [appimage-packages/blinken#3]
Between one of the commits we lost the main graphics. Needs invesitgation.

**Comment by ScarlettGatelyMoore** [comment]
connect(11, {sa_family=AF_LOCAL, sun_path="/run/user/1000/pulse/native"}, 110) = 0
stat("/tmp/.mount_jOgAQY/plugins/phonon4qt5_backend", 0x7ffcb6e8a810) = -1 ENOENT (No such file or directory)
stat("/tmp/.mount_jOgAQY/phonon4qt5_backend", 0x7ffcb6e8a810) = -1 ENOENT (No such file or directory)
write(2, "WARNING: bool Phonon::FactoryPri"..., 96WARNING: bool Phonon::FactoryPrivate::createBackend() phonon backend plugin could not be loaded
) = 96
stat("/tmp/.mount_jOgAQY/plugins/phonon4qt5_backend", 0x7ffcb6e8a870) = -1 ENOENT (No such file or directory)
stat("/tmp/.mount_jOgAQY/phonon4qt5_backend", 0x7ffcb6e8a870) = -1 ENOENT (No such file or directory)
write(2, "WARNING: bool Phonon::FactoryPri"..., 96WARNING: bool Phonon::FactoryPrivate::createBackend() phonon backend plugin could not be loaded
) = 96
stat("/tmp/.mount_jOgAQY/plugins/phonon4qt5_backend", 0x7ffcb6e8a9e0) = -1 ENOENT (No such file or directory)
stat("/tmp/.mount_jOgAQY/phonon4qt5_backend", 0x7ffcb6e8a9e0) = -1 ENOENT (No such file or directory)
write(2, "WARNING: bool Phonon::FactoryPri"..., 96WARNING: bool Phonon::FactoryPrivate::createBackend() phonon backend plugin could not be loaded
) = 96
write(8, "\1\0\0\0\0\0\0\0", 8)         = 8
write(8, "\1\0\0\0\0\0\0\0", 8)         = 8
stat("/tmp/.mount_jOgAQY/plugins/phonon4qt5_backend", 0x7ffcb6e8a880) = -1 ENOENT (No such file or directory)
stat("/tmp/.mount_jOgAQY/phonon4qt5_backend", 0x7ffcb6e8a880) = -1 ENOENT (No such file or directory)
write(2, "WARNING: bool Phonon::FactoryPri"..., 96WARNING: bool Phonon::FactoryPrivate::createBackend() phonon backend plugin could not be loaded
) = 96
write(2, "WARNING: Phonon::createPath: Can"..., 126WARNING: Phonon::createPath: Cannot connect  Phonon::MediaObject ( no objectName ) to  Phonon::AudioOutput ( no objectName ).
) = 126
stat("/home/scarlett/.local/share/blinken/sounds/lose.wav", 0x7ffcb6e8aaa0) = -1 ENOENT (No such file or directory)
stat("/usr/share/default-settings/plasma5-profile/blinken/sounds/lose.wav", 0x7ffcb6e8aaa0) = -1 ENOENT (No such file or directory)
stat("/usr/share/usr/share/xsessions/plasma/blinken/sounds/lose.wav", 0x7ffcb6e8aaa0) = -1 ENOENT (No such file or directory)
stat("/usr/local/share/blinken/sounds/lose.wav", 0x7ffcb6e8aaa0) = -1 ENOENT (No such file or directory)
stat("/usr/share/blinken/sounds/lose.wav", 0x7ffcb6e8aaa0) = -1 ENOENT (No such file or directory)
stat("/var/lib/snapd/desktop/blinken/sounds/lose.wav", 0x7ffcb6e8aaa0) = -1 ENOENT (No such file or directory)
stat("/home/scarlett/.local/share/blinken/sounds/1.wav", 0x7ffcb6e8aaa0) = -1 ENOENT (No such file or directory)
stat("/usr/share/default-settings/plasma5-profile/blinken/sounds/1.wav", 0x7ffcb6e8aaa0) = -1 ENOENT (No such file or directory)
stat("/usr/share/usr/share/xsessions/plasma/blinken/sounds/1.wav", 0x7ffcb6e8aaa0) = -1 ENOENT (No such file or directory)
stat("/usr/local/share/blinken/sounds/1.wav", 0x7ffcb6e8aaa0) = -1 ENOENT (No such file or directory)
stat("/usr/share/blinken/sounds/1.wav", 0x7ffcb6e8aaa0) = -1 ENOENT (No such file or directory)
stat("/var/lib/snapd/desktop/blinken/sounds/1.wav", 0x7ffcb6e8aaa0) = -1 ENOENT (No such file or directory)
stat("/home/scarlett/.local/share/blinken/sounds/2.wav", 0x7ffcb6e8aaa0) = -1 ENOENT (No such file or directory)
stat("/usr/share/default-settings/plasma5-profile/blinken/sounds/2.wav", 0x7ffcb6e8aaa0) = -1 ENOENT (No such file or directory)
stat("/usr/share/usr/share/xsessions/plasma/blinken/sounds/2.wav", 0x7ffcb6e8aaa0) = -1 ENOENT (No such file or directory)
stat("/usr/local/share/blinken/sounds/2.wav", 0x7ffcb6e8aaa0) = -1 ENOENT (No such file or directory)
stat("/usr/share/blinken/sounds/2.wav", 0x7ffcb6e8aaa0) = -1 ENOENT (No such file or directory)
stat("/var/lib/snapd/desktop/blinken/sounds/2.wav", 0x7ffcb6e8aaa0) = -1 ENOENT (No such file or directory)
stat("/home/scarlett/.local/share/blinken/sounds/3.wav", 0x7ffcb6e8aaa0) = -1 ENOENT (No such file or directory)
stat("/usr/share/default-settings/plasma5-profile/blinken/sounds/3.wav", 0x7ffcb6e8aaa0) = -1 ENOENT (No such file or directory)
stat("/usr/share/usr/share/xsessions/plasma/blinken/sounds/3.wav", 0x7ffcb6e8aaa0) = -1 ENOENT (No such file or directory)
stat("/usr/local/share/blinken/sounds/3.wav", 0x7ffcb6e8aaa0) = -1 ENOENT (No such file or directory)
stat("/usr/share/blinken/sounds/3.wav", 0x7ffcb6e8aaa0) = -1 ENOENT (No such file or directory)
stat("/var/lib/snapd/desktop/blinken/sounds/3.wav", 0x7ffcb6e8aaa0) = -1 ENOENT (No such file or directory)
stat("/home/scarlett/.local/share/blinken/sounds/4.wav", 0x7ffcb6e8aaa0) = -1 ENOENT (No such file or directory)
stat("/usr/share/default-settings/plasma5-profile/blinken/sounds/4.wav", 0x7ffcb6e8aaa0) = -1 ENOENT (No such file or directory)
stat("/usr/share/usr/share/xsessions/plasma/blinken/sounds/4.wav", 0x7ffcb6e8aaa0) = -1 ENOENT (No such file or directory)
stat("/usr/local/share/blinken/sounds/4.wav", 0x7ffcb6e8aaa0) = -1 ENOENT (No such file or directory)
stat("/usr/share/blinken/sounds/4.wav", 0x7ffcb6e8aaa0) = -1 ENOENT (No such file or directory)
stat("/var/lib/snapd/desktop/blinken/sounds/4.wav", 0x7ffcb6e8aaa0) = -1 ENOENT (No such file or directory)
stat("/home/scarlett/.local/share/blinken/images/blinken.svg", 0x7ffcb6e8abb0) = -1 ENOENT (No such file or directory)
stat("/usr/share/default-settings/plasma5-profile/blinken/images/blinken.svg", 0x7ffcb6e8abb0) = -1 ENOENT (No such file or directory)
stat("/usr/share/usr/share/xsessions/plasma/blinken/images/blinken.svg", 0x7ffcb6e8abb0) = -1 ENOENT (No such file or directory)
stat("/usr/local/share/blinken/images/blinken.svg", 0x7ffcb6e8abb0) = -1 ENOENT (No such file or directory)
stat("/usr/share/blinken/images/blinken.svg", 0x7ffcb6e8abb0) = -1 ENOENT (No such file or directory)
stat("/var/lib/snapd/desktop/blinken/images/blinken.svg", 0x7ffcb6e8abb0) = -1 ENOENT (No such file or directory)
write(2, "QFSFileEngine::open: No file nam"..., 44QFSFileEngine::open: No file name specified
) = 44
write(2, "Cannot open file '', because: No"..., 53Cannot open file '', because: No file name specified
) = 53
access("/etc/kde5rc", R_OK)             = -1 ENOENT (No such file or directory)
stat("/home/scarlett/.config/blinkenrc", 0x7ffcb6e8a980) = -1 ENOENT (No such file or directory)


It is not using anything in /tmp/.mount*/./usr/share 
clearly something I missed here.

**Comment by star-buck** [comment]
What did you commit?

**Comment by ScarlettGatelyMoore** [comment]
I upgraded qt to 5.7.1 needed by some apps and discovered the host QT was being used. I fixed that now and now fixing the other bits that broke including this.

**Comment by ScarlettGatelyMoore** [comment]
Now that host qt is not being used ( good ) it has exposed several plugins are missing. I have set to manual copy, but now I have discovered a few plugins are completely missing in the docker image. Rebuilding Qt now with this hopefully fixed. Will test tonight when I get home.

**Comment by ScarlettGatelyMoore** [comment]
Giving up on this one for a bit, I have tried so many things and I don't want to spend enormous amounts of time on one app again ( vlc.. ) It is clear that host libs are being called
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe7447700 (LWP 6562)]
[New Thread 0x7fffe66d2700 (LWP 6563)]
WARNING: bool Phonon::FactoryPrivate::createBackend() phonon backend plugin could not be loaded
WARNING: bool Phonon::FactoryPrivate::createBackend() phonon backend plugin could not be loaded
WARNING: bool Phonon::FactoryPrivate::createBackend() phonon backend plugin could not be loaded
WARNING: bool Phonon::FactoryPrivate::createBackend() phonon backend plugin could not be loaded
WARNING: bool Phonon::FactoryPrivate::createBackend() phonon backend plugin could not be loaded
WARNING: Phonon::createPath: Cannot connect  Phonon::MediaObject ( no objectName ) to  Phonon::AudioOutput ( no objectName ).
QFSFileEngine::open: No file name specified
Cannot open file '', because: No file name specified

Thread 1 "AppRun" received signal SIGSEGV, Segmentation fault.
0x0000000000659cf0 in ?? ()
(gdb) bt 0x0000000000659cf0
#0  0x0000000000659cf0 in ?? ()
#1  0x00007ffff7f86d7b in ?? () from /tmp/.mount_G5ncsG/plugins/xcbglintegrations/libqxcb-glx-integration.so
#2  0x00007fffe9c50441 in QXcbIntegration::createPlatformWindow(QWindow*) const () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#3  0x00007ffff5cc0aea in QWindowPrivate::create(bool) () from /tmp/.mount_G5ncsG/lib/libQt5Gui.so.5
#4  0x00007ffff62f65ed in QWidgetPrivate::create_sys(unsigned long long, bool, bool) () from /tmp/.mount_G5ncsG/lib/libQt5Widgets.so.5
#5  0x00007ffff62f5d99 in QWidget::create(unsigned long long, bool, bool) () from /tmp/.mount_G5ncsG/lib/libQt5Widgets.so.5
#6  0x00007ffff63016ea in QWidget::setVisible(bool) () from /tmp/.mount_G5ncsG/lib/libQt5Widgets.so.5
#7  0x000000000040bf0a in ?? ()
#8  0x000000000040afa2 in _start ()
and it looks like the  /tmp/.mount_G5ncsG/plugins/xcbglintegrations/libqxcb-glx-integration.so plugin is to blame. I just don't know how to force them to use the correct libs. They are properly brought in by linuxdeployqt. @probono have any ideas?

**Comment by ScarlettGatelyMoore** [comment]
Now fixed.
