### ISSUE TITLE
Does not run, missing libKF5XmlGui.so.5

### ISSUE THREAD

**Issue by probonopd** [appimage-packages/blinken#4]
```
blinken-git12082016-x86_64.AppImage: error while loading shared libraries: libKF5XmlGui.so.5: cannot open shared object file: No such file or directory
```

`usr/lib/x86_64-linux-gnu/libKF5XmlGui.so` exists but `usr/bin/blinken` does not search there for libraries because its rpath is wrong:

```
patchelf  --print-rpath usr/bin/blinken
/app././/lib/x86_64-linux-gnu:/opt././/lib:/app././/lib
```

If I change the rpath:

```
patchelf  --set-rpath '$ORIGIN/../lib/x86_64-linux-gnu:$ORIGIN/../lib/'usr/bin/blinken
```

then we get 

```
usr/bin/blinkensquashfs-root/usr/bin/blinken: error while loading shared libraries: libQt5PrintSupport.so.5: cannot open shared object file: No such file or directory
```

which means that `libKF5XmlGui.so.5.29.0` is trying to load `libQt5PrintSupport.so.5` but from the wrong rpath also. So it looks like the whole rpath thing is not working correctly yet. Maybe we should go back to using LD_LIBRARY_PATH for now until `linuxdeployqt` is working properly.

**Comment by ScarlettGatelyMoore** [comment]
Yikes, you tested this in the middle of a QT upgrade. I have this all sorted now. You can test todays build to verify.

**Comment by star-buck** [comment]
Nitpick: It's Qt ( QT was/is Apple QuickTime :)
