### ISSUE TITLE
blinken executable exists in 2 places

### ISSUE THREAD

**Issue by probonopd** [appimage-packages/blinken#5]
Please pick one but don't mix:

1. $APPDIR/usr/lib/blinken (FHS-like bundle; recommended but not yet supported by `linuxdeployqt` yet)
2. $APPDIR/blinken (`linuxdeployqt`-style bundle)

**Comment by ScarlettGatelyMoore** [comment]
The first one should not exist... can you  please tell me how you are opening these? Ark no longer opens them for me.

**Comment by probonopd** [comment]
Ark can't handle type-2 (squashfs-based) AppImages yet.
`./Your.AppImage --appimage-offset` gives you an offset, say 123456
then you can mount it using `sudo mount ./Your.AppImage /mnt -o offset,123456`
